// <auto-generated />
using System;
using IeltsPlatform.ApiService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IeltsPlatform.ApiService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251113073013_SeedBlogData")]
    partial class SeedBlogData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IeltsPlatform.ApiService.Models.Blog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BlogContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BlogName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Theme")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            BlogContent = "Master IELTS Reading with these essential tips:\n1. Time management is crucial\n2. Skim and scan effectively\n3. Practice different question types\n4. Build your vocabulary\n5. Read academic articles regularly",
                            BlogName = "IELTS Reading Tips and Strategies",
                            CreatedAt = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Theme = 1,
                            UpdatedAt = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("91f5ca49-8983-4390-937d-ecd4907082e2"),
                            BlogContent = "Improve your IELTS Speaking Part 2 performance:\n1. Structure your response (past, present, future)\n2. Include personal experiences\n3. Use advanced vocabulary\n4. Practice time management (2 minutes)\n5. Record yourself speaking",
                            BlogName = "How to Excel in IELTS Speaking Part 2",
                            CreatedAt = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Theme = 2,
                            UpdatedAt = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("17c59ee6-33fa-4310-8480-772a047f18f6"),
                            BlogContent = "Perfect your IELTS Writing Task 2 structure:\n1. Introduction\n   - Background statement\n   - Thesis statement\n2. Body Paragraphs\n   - Topic sentences\n   - Supporting points\n   - Examples\n3. Conclusion\n   - Restate main points\n   - Final thoughts",
                            BlogName = "IELTS Writing Task 2: Essay Structure",
                            CreatedAt = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Theme = 3,
                            UpdatedAt = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("7238e7b3-52fc-4354-ab67-2940cacc2ae5"),
                            BlogContent = "Enhance your listening skills with these note-taking strategies:\n1. Use abbreviations\n2. Focus on keywords\n3. Practice prediction\n4. Listen for signpost words\n5. Review and transfer answers carefully",
                            BlogName = "IELTS Listening: Note-Taking Techniques",
                            CreatedAt = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Theme = 0,
                            UpdatedAt = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
