// <auto-generated />
using System;
using IeltsPlatform.ApiService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IeltsPlatform.ApiService.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    partial class BlogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IeltsPlatform.ApiService.Entities.Blog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BlogContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BlogName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Theme")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            BlogContent = "Master IELTS Reading with these essential tips:\r\n                         1. Time management is crucial\r\n                         2. Skim and scan effectively\r\n                         3. Practice different question types\r\n                         4. Build your vocabulary\r\n                         5. Read academic articles regularly",
                            BlogName = "IELTS Reading Tips and Strategies",
                            CreatedAt = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Theme = 0,
                            UpdatedAt = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("7494c2de-1f38-4a75-8580-8be0a4eee505"),
                            BlogContent = "Improve your IELTS Speaking Part 2 performance:\r\n                         1. Structure your response (past, present, future)\r\n                         2. Include personal experiences\r\n                         3. Use advanced vocabulary\r\n                         4. Practice time management (2 minutes)\r\n                         5. Record yourself speaking",
                            BlogName = "How to Excel in IELTS Speaking Part 2",
                            CreatedAt = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Theme = 2,
                            UpdatedAt = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("f85fe85d-46f3-41bb-8dbb-49cc5f09b55a"),
                            BlogContent = "Perfect your IELTS Writing Task 2 structure:\r\n                         1. Introduction\r\n                            - Background statement\r\n                            - Thesis statement\r\n                         2. Body Paragraphs\r\n                            - Topic sentences\r\n                            - Supporting points\r\n                            - Examples\r\n                         3. Conclusion\r\n                            - Restate main points\r\n                            - Final thoughts",
                            BlogName = "IELTS Writing Task 2: Essay Structure",
                            CreatedAt = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Theme = 1,
                            UpdatedAt = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = new Guid("7213d0f3-e858-41b0-aa4f-1d137218249b"),
                            BlogContent = "Enhance your listening skills with these note-taking strategies:\r\n                         1. Use abbreviations\r\n                         2. Focus on keywords\r\n                         3. Practice prediction\r\n                         4. Listen for signpost words\r\n                         5. Review and transfer answers carefully",
                            BlogName = "IELTS Listening: Note-Taking Techniques",
                            CreatedAt = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            Theme = 3,
                            UpdatedAt = new DateTime(2025, 11, 5, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
